version: 0.0.1


services:
  api:
    container_name: multisistema_api
    image: node:18-alpine
    command: sh -c "npm install && npm install -g nodemon &&  npm run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./api:/app
  push:
    container_name: multisistema_push
    image: node:18-alpine
    command: sh -c "npm install && npm install -g nodemon &&  npm run dev"
    ports:
      - 127.0.0.1:3001:3001
    working_dir: /app
    volumes:
      - ./push:/app
  db:
    container_name: multisistema_db
    image: mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: multisistema

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080