version: 0.0.1


services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm install -g nodemon &&  npm run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: multisistema

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080