### Авторизация пользователя
POST http://localhost:3000/api/auth/signIn
Content-Type: application/json

{
  "login": "zharkov_s@multisistema.ru",
  "password": "123456"
}


### Получить все объекты пользователя
GET http://localhost:3000/api/object/objects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNTM5Mjg4NiwiZXhwIjoxNzA1NDc5Mjg2fQ.-x38vdXkK3utOwD3ejQQb9ul1wB46ngga2TTRZ0fDl0

### Получить один объект пользователя
GET http://localhost:3000/api/object/objectFull/3055
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwMzMzMDg5NCwiZXhwIjoxNzAzNDE3Mjk0fQ.8GsYYfxyqf_sV32yZnQEn1o8Tq3oyuCkQu0pwTbX1Qk


### Получить даные по объету пользователя
GET http://localhost:3000/api/meter/meter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNDY0MTIzOSwiZXhwIjoxNzA0NzI3NjM5fQ.VNO-QLDI01QaEggbO1aS_1MdMmNrpwUdzcQZ0_w_06k
Content-Type: application/json

{
  "idObject": 3118,
  "date": "2024-01-06T00:00:00.000"
}

###
GET http://localhost:3000/api/pay/tariff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNTM5Mjg4NiwiZXhwIjoxNzA1NDc5Mjg2fQ.-x38vdXkK3utOwD3ejQQb9ul1wB46ngga2TTRZ0fDl0
Content-Type: application/json

###
GET http://localhost:3000/api/pay/tariff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNTM5Mjg4NiwiZXhwIjoxNzA1NDc5Mjg2fQ.-x38vdXkK3utOwD3ejQQb9ul1wB46ngga2TTRZ0fDl0
Content-Type: application/json
###
GET http://localhost:3000/api/pay/allTariffObject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNTM5Mjg4NiwiZXhwIjoxNzA1NDc5Mjg2fQ.-x38vdXkK3utOwD3ejQQb9ul1wB46ngga2TTRZ0fDl0
Content-Type: application/json

###
POST http://localhost:3000/api/pay/pay
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNTM5Mjg4NiwiZXhwIjoxNzA1NDc5Mjg2fQ.-x38vdXkK3utOwD3ejQQb9ul1wB46ngga2TTRZ0fDl0
Content-Type: application/json