### Авторизация пользователя
POST http://localhost:3000/api/auth/signIn
Content-Type: application/json

{
  "login": "zharkov_s@multisistema.ru",
  "password": "123456"
}


### Получить все объекты пользователя
GET http://localhost:3000/api/object/objects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwMzg4MzIyNywiZXhwIjoxNzAzOTY5NjI3fQ.Q-lcSuQNx4bq4XCtteI02cPhxow_NHaZE0PzUUP5fZ4

### Получить один объект пользователя
GET http://localhost:3000/api/object/objectFull/3055
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwMzMzMDg5NCwiZXhwIjoxNzAzNDE3Mjk0fQ.8GsYYfxyqf_sV32yZnQEn1o8Tq3oyuCkQu0pwTbX1Qk


### Получить даные по объету пользователя
GET http://localhost:3000/api/meter/meter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InpoYXJrb3Zfc0BtdWx0aXNpc3RlbWEucnUiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcwNDY0MTIzOSwiZXhwIjoxNzA0NzI3NjM5fQ.VNO-QLDI01QaEggbO1aS_1MdMmNrpwUdzcQZ0_w_06k
Content-Type: application/json

{
  "idObject": 3118,
  "date": "2024-01-06T00:00:00.000"
}

###
GET http://localhost:1000/api/pay/tariff
Content-Type: application/json

###
GET https://run.mocky.io/v3/35e0d18e-2521-4f1b-a575-f0fe366f66e3
Content-Type: application/json
